### ISSUE TITLE
crawl apple/appleRealtime fail

### ISSUE THREAD

**Issue by elleryq** [TaiwanStat/Taiwan-news-crawlers#2]
依照 README 操作，出現 `TypeError: 'float' object is not iterable` 錯誤。

```
scrapy crawl apple -o apple_news.json
2018-03-07 11:25:33 [scrapy.utils.log] INFO: Scrapy 1.3.0 started (bot: TaiwanNewsCrawler)
2018-03-07 11:25:33 [scrapy.utils.log] INFO: Overridden settings: {'SPIDER_MODULES': ['TaiwanNewsCrawler.spiders'], 'FEED_FORMAT': 'json', 'FEED_URI': 'apple_news.json', 'BOT_NAME': 'TaiwanNewsCrawler', 'NEWSPIDER_MODULE': 'TaiwanNewsCrawler.spiders'}
2018-03-07 11:25:33 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.logstats.LogStats']
2018-03-07 11:25:33 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2018-03-07 11:25:33 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2018-03-07 11:25:33 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2018-03-07 11:25:33 [scrapy.core.engine] INFO: Spider opened
2018-03-07 11:25:33 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-03-07 11:25:33 [scrapy.extensions.telnet] DEBUG: Telnet console listening on 127.0.0.1:6023
2018-03-07 11:25:33 [scrapy.core.scraper] ERROR: Error downloading <GET https://tw.appledaily.com/daily>
Traceback (most recent call last):
  File "/home/ellery/.virtualenvs/taiwan-news-crawlers/lib/python3.4/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/ellery/.virtualenvs/taiwan-news-crawlers/lib/python3.4/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/ellery/.virtualenvs/taiwan-news-crawlers/lib/python3.4/site-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "/home/ellery/.virtualenvs/taiwan-news-crawlers/lib/python3.4/site-packages/scrapy/utils/defer.py", line 45, in mustbe_deferred
    result = f(*args, **kw)
  File "/home/ellery/.virtualenvs/taiwan-news-crawlers/lib/python3.4/site-packages/scrapy/core/downloader/handlers/__init__.py", line 65, in download_request
    return handler.download_request(request, spider)
  File "/home/ellery/.virtualenvs/taiwan-news-crawlers/lib/python3.4/site-packages/scrapy/core/downloader/handlers/http11.py", line 61, in download_request
    return agent.download_request(request)
  File "/home/ellery/.virtualenvs/taiwan-news-crawlers/lib/python3.4/site-packages/scrapy/core/downloader/handlers/http11.py", line 286, in download_request
    method, to_bytes(url, encoding='ascii'), headers, bodyproducer)
  File "/home/ellery/.virtualenvs/taiwan-news-crawlers/lib/python3.4/site-packages/twisted/web/client.py", line 1655, in request
    parsedURI.originForm)
  File "/home/ellery/.virtualenvs/taiwan-news-crawlers/lib/python3.4/site-packages/twisted/web/client.py", line 1432, in _requestWithEndpoint
    d = self._pool.getConnection(key, endpoint)
  File "/home/ellery/.virtualenvs/taiwan-news-crawlers/lib/python3.4/site-packages/twisted/web/client.py", line 1318, in getConnection
    return self._newConnection(key, endpoint)
  File "/home/ellery/.virtualenvs/taiwan-news-crawlers/lib/python3.4/site-packages/twisted/web/client.py", line 1330, in _newConnection
    return endpoint.connect(factory)
  File "/home/ellery/.virtualenvs/taiwan-news-crawlers/lib/python3.4/site-packages/twisted/internet/endpoints.py", line 2092, in connect
    self._wrapperFactory(protocolFactory)
  File "/home/ellery/.virtualenvs/taiwan-news-crawlers/lib/python3.4/site-packages/twisted/internet/endpoints.py", line 903, in connect
    EndpointReceiver, self._hostText, portNumber=self._port
  File "/home/ellery/.virtualenvs/taiwan-news-crawlers/lib/python3.4/site-packages/twisted/internet/_resolver.py", line 189, in resolveHostName
    onAddress = self._simpleResolver.getHostByName(hostName)
  File "/home/ellery/.virtualenvs/taiwan-news-crawlers/lib/python3.4/site-packages/scrapy/resolver.py", line 21, in getHostByName
    d = super(CachingThreadedResolver, self).getHostByName(name, timeout)
  File "/home/ellery/.virtualenvs/taiwan-news-crawlers/lib/python3.4/site-packages/twisted/internet/base.py", line 276, in getHostByName
    timeoutDelay = sum(timeout)
TypeError: 'float' object is not iterable
2018-03-07 11:25:33 [scrapy.core.engine] INFO: Closing spider (finished)
2018-03-07 11:25:33 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/exception_count': 1,
 'downloader/exception_type_count/builtins.TypeError': 1,
 'downloader/request_bytes': 220,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 3, 7, 3, 25, 33, 521731),
 'log_count/DEBUG': 1,
 'log_count/ERROR': 1,
 'log_count/INFO': 7,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2018, 3, 7, 3, 25, 33, 203939)}
2018-03-07 11:25:33 [scrapy.core.engine] INFO: Spider closed (finished)
```

**Comment by ching56** [comment]
@elleryq 你好，謝謝你的回報
將 twisted 版本降到 16.6.0 也許可以解決這個問題
1. http://blog.csdn.net/ziven2012/article/details/60959518
2. https://github.com/scrapy/scrapy/issues/2648

**Comment by elleryq** [comment]
好的!我試試看 :)

**Comment by elleryq** [comment]
的確可以了，謝謝你。
